version: "3.9"

services:
  order_genie_postgres:
    image: postgres:17.0
    container_name: order_genie_postgres
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    networks:
      - order_genie
    env_file:
      - .env

networks:
  order_genie:
    driver: bridge
