"""empty message

Revision ID: 2543622b4e7c
Revises: 813a46f4eb43
Create Date: 2025-06-08 17:18:47.796767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2543622b4e7c"
down_revision: Union[str, None] = "813a46f4eb43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """INSERT INTO menu_items (name, description, price, created_by, updated_by, active)
            VALUES
            ('Cheeseburger', 'Juicy beef patty topped with melted cheese, lettuce, and tomato on a toasted bun.', 8.99, 'app_service', 'app_service', TRUE),
            ('Chicken Wings', 'Crispy fried chicken wings tossed in your choice of sauce.', 10.99, 'app_service', 'app_service', TRUE),
            ('Veggie Wrap', 'Whole wheat wrap filled with roasted vegetables, hummus, and mixed greens.', 7.99, 'app_service', 'app_service', TRUE),
            ('Fries', 'Thick-cut potato fries cooked to a crispy perfection.', 4.99, 'app_service', 'app_service', TRUE),
            ('Grilled Chicken Salad', 'Mixed greens topped with grilled chicken, cherry tomatoes, cucumber, and balsamic vinaigrette.', 12.99, 'app_service', 'app_service', TRUE),
            ('Meatball Sub', 'Juicy meatballs topped with marinara sauce and melted mozzarella cheese on a crusty sub roll.', 9.99, 'app_service', 'app_service', TRUE),
            ('Onion Rings', 'Crispy onion rings battered to perfection.', 5.99, 'app_service', 'app_service', TRUE),
            ('Chicken Quesadilla', 'Shredded chicken, cheese, and sautéed onions wrapped in a flour tortilla.', 8.99, 'app_service', 'app_service', TRUE),
            ('Greek Salad', 'Mixed greens topped with feta cheese, olives, cucumber, and Greek vinaigrette.', 11.99, 'app_service', 'app_service', TRUE),
            ('Bacon Cheeseburger', 'Juicy beef patty topped with crispy bacon, melted cheese, lettuce, and tomato on a toasted bun.', 10.99, 'app_service', 'app_service', TRUE);"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
